retain_objc_accessible: true
retain_public: true
schemes:
- Analytics
- Logger
- Messaging
- Models
- MyChat
- Services
- UI
targets:
- Analytics
- Logger
- Messaging
- Models
- MyChat
- Services
- UI
workspace: MyChat.xcworkspace
