included: # paths to include during linting. `--path` is ignored if present.
  - MyChat

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - orphaned_doc_comment
  - cyclomatic_complexity
  - function_body_length
  - function_parameter_count

